---
- hosts: all
  tasks:
  - name: Set hostname
    hostname: name='{{ inventory_hostname }}'
  - name: Install Cert
    command: "/usr/bin/yum -y localinstall http://sat.example.com/pub/katello-ca-consumer-latest.noarch.rpm"
  - name: Register with Satellite
    command: "/usr/sbin/subscription-manager register --org Default_Organization --force --activationkey rhel7"
    register: registered
  - name: Enable Repositories
    command: subscription-manager repos --enable=rhel-7-server-satellite-tools-6.2-rpms
    when: registered|success
  - name: Install Katello Agent
    yum: pkg=katello-agent state=latest
    when: registered|success
    notify:
    - Enable Katello Agent
    - Start Katello Agent
  - name: Update all packages
    command: "/usr/bin/yum -y update -x kernel"
  handlers:
  - name: Enable Katello Agent
    service: name=goferd enabled=yes
  - name: Start Katello Agent
    service: name=goferd state=started
